import '../models/block.dart';

int _t(int h, int m) => h * 60 + m;

final List<Block> defaultBlocks = [
  Block(
    title: 'Wake up',
    description: 'Get up, hydrate, fresh air',
    startMinutes: _t(5, 30),
    endMinutes: _t(6, 0),
    orderIndex: 0,
    priority: Priority.rest,
  ),
  Block(
    title: 'Travel 360 Standup',
    description: 'Be sharp — defines visibility',
    startMinutes: _t(6, 15),
    endMinutes: _t(7, 15),
    orderIndex: 1,
    priority: Priority.core,
  ),
  Block(
    title: 'Deep Work — Travel 360',
    description: 'React features, Node APIs, real bugs. Best energy.',
    startMinutes: _t(7, 15),
    endMinutes: _t(10, 0),
    orderIndex: 2,
    priority: Priority.core,
  ),
  Block(
    title: 'Cooking + Breakfast',
    description: '',
    startMinutes: _t(10, 0),
    endMinutes: _t(11, 0),
    orderIndex: 3,
    priority: Priority.meal,
  ),
  Block(
    title: 'Travel 360 Execution',
    description: 'Continue tasks, push progress, follow-ups',
    startMinutes: _t(11, 0),
    endMinutes: _t(13, 30),
    orderIndex: 4,
    priority: Priority.core,
  ),
  Block(
    title: 'Lunch + Rest',
    description: '',
    startMinutes: _t(13, 30),
    endMinutes: _t(14, 15),
    orderIndex: 5,
    priority: Priority.meal,
  ),
  Block(
    title: 'Incube — WhatsApp / Meta API',
    description: 'Spring Boot, Meta integration. Focused but limited.',
    startMinutes: _t(14, 15),
    endMinutes: _t(16, 0),
    orderIndex: 6,
    priority: Priority.secondary,
  ),
  Block(
    title: 'Light Work',
    description: 'Bug fixes, replies, small tasks',
    startMinutes: _t(16, 0),
    endMinutes: _t(17, 0),
    orderIndex: 7,
    priority: Priority.secondary,
  ),
  Block(
    title: 'Recovery (Rest / Walk / Nap)',
    description: 'Non-negotiable. Keeps you alive mentally.',
    startMinutes: _t(17, 0),
    endMinutes: _t(18, 0),
    orderIndex: 8,
    priority: Priority.rest,
  ),
  Block(
    title: 'Dinner',
    description: '',
    startMinutes: _t(18, 0),
    endMinutes: _t(19, 0),
    orderIndex: 9,
    priority: Priority.meal,
  ),
  Block(
    title: 'Exam Prep',
    description: 'Important topics only',
    startMinutes: _t(19, 0),
    endMinutes: _t(20, 0),
    orderIndex: 10,
    priority: Priority.exam,
  ),
  Block(
    title: 'Skill Upgrade — Travel 360',
    description: 'Rotate: React internals / Node perf / API design / debugging',
    startMinutes: _t(20, 0),
    endMinutes: _t(21, 0),
    orderIndex: 11,
    priority: Priority.skill,
  ),
  Block(
    title: 'Sleep',
    description: 'Lights out',
    startMinutes: _t(21, 30),
    endMinutes: _t(22, 0),
    orderIndex: 12,
    priority: Priority.rest,
  ),
];
